### PR TITLE
Remove SCons/SBMS

### PR DESCRIPTION
**Pull request by nathanwbrei**
Up until now JANA could be built using either CMake or SCons. However:

1. The C++ community has been rapidly converging towards CMake. This
   means tight IDE integration and tooling. It also means better
   integration with external projects which also use CMake (e.g. specifying
   version constraints and importing subprojects) and opens
   the door for better integration with package managers in the future.

2. Supporting SCons takes time and offers no added value over CMake.
   SCons support is already falling behind. Furthermore, SCons is missing
   a lot of functionality present in CMake (e.g. creating files from
   templates), and we have been adding this functionality ourselves in
   SBMS. The learning curve for a new developer is much higher because
   they have to figure out the custom, ad-hoc SBMS way of doing things,
   instead of using the standard CMake idioms.

### CODE REVIEW

**Comment by nathanwbrei** [comment]
Let's not merge, at least until ejpm has been updated to build using cmake instead.

**Comment by DraTeots** [comment]
I switched ejpm to run CMake and have the next problem:

1. Zmq is required
```
-- Could NOT find ZEROMQ (missing: ZEROMQ_LIBRARY ZEROMQ_INCLUDE_DIR) 
-- Could NOT find CZMQ (missing: CZMQ_LIBRARY CZMQ_INCLUDE_DIR) 
```

CZMQ is optional, but ZEROMQ is required. 

2. CMake is still 3.13 in v2.0.2 =)

**Comment by DraTeots** [comment]
CMake is still 3.13 in some files like at src/plugins/janacontrol/CMakeLists.txt

**Comment by faustus123** [comment]
Hi Dmitry,

I put in a fix for the make version which lowered it to make 3.9. I looked through the other CMakeLists.txt files and could
not find any others with the 3.13 requirement. We should probably find a way to consolidate all of these so the version
requirement shows up in only one place.

Regarding the ZEROMQ issue: I was unable to reproduce it. I built on a system with no ZMQ installation and saw the same
warning messages, but the build continued and succeeded. Can you confirm the the build really failed? For me it printed
lots of scary red colored messages, but they were all just warnings and not actually errors.

Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Mar 12, 2020, at 8:09 PM, Dmitry Romanov <notifications@github.com<mailto:notifications@github.com>> wrote:



CMake is still 3.13 in some files like at src/plugins/janacontrol/CMakeLists.txt

**Comment by nathanwbrei** [comment]
@DraTeots 

I updated the v2.0.2 tag to include David's and my changes. As of a minute ago, the CZMQ dependency is gone completely, so if you ever see so much as the string "CZMQ" when building JANA it means you should git fetch and clear your CMake cache.

**Comment by nathanwbrei** [comment]
@faustus123 

The src/plugins/janacontrol/CMakeLists.txt shouldn't have any of the CMake project declaration boilerplate. All it needs is "add_subdirectory(src)". I've updated it accordingly.

I think what happened was that you created the janacontrol plugin using `jana-generate.py plugin janacontrol`. As of some time last week, the `plugin` option was bifurcated into `StandalonePlugin` and `ProjectPlugin`. The former creates a project root CMakeLists boilerplate, and the latter assumes it already exists in some parent directory.

**Comment by nathanwbrei** [comment]
@DraTeots I think it's safe for you to try building in Docker again.

**Comment by faustus123** [comment]
Is this now still pending? Github claims there are now conflicting files that need to be resolved. The PR also changes 230 files which seems like a lot given what the description says it is for. I'm just wondering if the branch this pulling from should be updated to get some other changes that have since gone into master.

**Pull request merged**
