### PR TITLE
Add SubeventCUDAExample

### PR DESCRIPTION
**Pull request by cissieAB**
Should be able to merge now.

### CODE REVIEW

**Comment by cissieAB** [comment]
@nathanwbrei @faustus123 :arrow_up: See the above PR. CUDA is working for the first 4 events. Then a segfault is involved which I do not quite understand.

**Comment by faustus123** [comment]
I quickly scanned the code and agree that I don't see why this should crash if the original (non-CUDA) version doesn't. I started trying to follow how the outputs from the subevent task are managed and inserted back into the JFactoryT, but realized quickly it would take a bit to trace through.

The stack trace indicates the crash is happening in `JFactoryT<MyOutput>::ClearData()`. The fact that it is not complaining about something related to freeing memory makes me suspect the pointer to the `JFactoryT<MyOutput>` object itself may be invalid. 

Could you turn on debugging symbols so the backtrace will show line numbers? May be helpful as we try and debug this.

**Comment by cissieAB** [comment]
@faustus123 I add "set(CMAKE_BUILD_TYPE "Debug")" to cmake and get the below from gdb
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6afd700 (LWP 110309)]
0x000000000043415d in JFactoryT<MyOutput>::ClearData (this=0x7ffff0555390)
    at /home/xmei/projects/JANA2/src/libraries/JANA/JFactoryT.h:214
214	            for (auto p : mData) delete p;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 nvidia-driver-latest-dkms-cuda-libs-470.57.02-1.el7.x86_64
(gdb) where
#0  0x000000000043415d in JFactoryT<MyOutput>::ClearData (this=0x7ffff0555390)
    at /home/xmei/projects/JANA2/src/libraries/JANA/JFactoryT.h:214
#1  0x000000000044dcc2 in JFactorySet::Release() ()
#2  0x0000000000465864 in JEventPool::get(unsigned long) ()
#3  0x0000000000464b9c in JEventSourceArrow::execute(JArrowMetrics&, unsigned long) ()
#4  0x0000000000467cb8 in JWorker::loop() ()
#5  0x0000000000469acd in void std::__invoke_impl<void, void (JWorker::*)(), JWorker*>(std::__invoke_memfun_deref, void (JWorker::*&&)(), JWorker*&&) ()
#6  0x0000000000469a0f in std::__invoke_result<void (JWorker::*)(), JWorker*>::type std::__invoke<void (JWorker::*)(), JWorker*>(void (JWorker::*&&)(), JWorker*&&) ()
#7  0x000000000046997f in void std::thread::_Invoker<std::tuple<void (JWorker::*)(), JWorker*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
#8  0x0000000000469938 in std::thread::_Invoker<std::tuple<void (JWorker::*)(), JWorker*> >::operator()() ()
#9  0x000000000046991c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (JWorker::*)(), JWorker*> > >::_M_run() ()
#10 0x00007ffff74b3df0 in execute_native_thread_routine ()
    at ../../../../../srcdir/libstdc++-v3/src/c++11/thread.cc:80
#11 0x00007ffff79c2ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff6bfcb0d in clone () from /lib64/libc.so.6
```

I find another interesting thing, CUDA launch 2 more CPU threads, see LWP 11031[2-3] as below. 
```
[INFO] Starting processing with 1 threads requested...
[INFO] JArrowProcessingController: run(): Launching 1 workers
[New Thread 0x7ffff6afd700 (LWP 110309)]
[DEBUG] JWorker: Worker 0 has entered loop().
[DEBUG] JScheduler: Worker 0, idle, NotRunYet => simpleSource  [1 threads]
[INFO] Emitting event 0
[INFO] Emitting event 1
[INFO] Emitting event 2
[INFO] Emitting event 3
[DEBUG] JScheduler: Worker 0, simpleSource, ComeBackLater => split  [1 threads]
[DEBUG] JWorker: Worker 0 succeeded at split
[DEBUG] JWorker: Worker 0 succeeded at split
[DEBUG] JWorker: Worker 0 succeeded at split
[DEBUG] JScheduler: Worker 0, split, ComeBackLater => subprocess  [1 threads]
[INFO] Processing subevent 0:0
[INFO]     Before CUDA, evt:sub=-1:-1
[New Thread 0x7ffff4ba0700 (LWP 110312)]
[New Thread 0x7fffe9fff700 (LWP 110313)]
[INFO]     After CUDA, evt:sub=0:0
```

**Comment by faustus123** [comment]
@cissieAB I downloaded and compiled your fork/branch. I was able to reproduce the seg. fault. I modified it to have a CPU version of the kernel so I could easily run in either GPU or CPU mode. I put a breakpoint on the line where the crash is happening (JFactoryT.h:214) and printed the contents of the first MyOutput object just before it is deleted. You can see the relevant parts of the gdb sessions below.

The thing I notice is that the `vptr` for the `JObject` part of the MyObject is set to `0x0` when running on the GPU. I then ran it through again and verified that it is getting overwritten during the copy of the `MyOutput` from device memory to host memory. This would make sense that when it goes to destruct the `JObject` part of `MyOutput` it gets a seg fault. I think what is going on is that since the `MyOutput` object is simply allocated as memory and not actually constructed, the `vptr` is never properly set for the object on the device. If I add the following before the kernel call, then it works properly:

~~~
cudaMemcpy(d_out, h_out, sizeof(MyOutput), cudaMemcpyHostToDevice);
~~~ 


Run with GPU
-----------------------------------------------------------------
~~~bash
Thread 2 "SubeventExample" hit Breakpoint 1, JFactoryT<MyInput>::ClearData (this=0x7ffff0001e50)
    at /home/davidl/work/2022.11.13.JANA2_CUDA/JANA2_cissieAB/src/libraries/JANA/JFactoryT.h:214
214	            for (auto p : mData) delete p;
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 nvidia-driver-latest-dkms-cuda-libs-510.47.03-1.el7.x86_64
(gdb) print *mData[0]
$1 = {<JObject> = {_vptr.JObject = 0x59c528 <vtable for MyInput+16>, associated = std::set with 0 elements, auto_delete = std::set with 0 elements}, 
  x = 22, y = 3.5999999, evt = 3, sub = 0}
(gdb) cont
Continuing.

Thread 2 "SubeventExample" hit Breakpoint 1, JFactoryT<MyOutput>::ClearData (this=0x7ffff02f5bd0)
    at /home/davidl/work/2022.11.13.JANA2_CUDA/JANA2_cissieAB/src/libraries/JANA/JFactoryT.h:214
214	            for (auto p : mData) delete p;
(gdb) print *mData[0]
$2 = {<JObject> = {_vptr.JObject = 0x0, associated = std::set with 0 elements, auto_delete = std::set with 0 elements}, z = 25.6000004, evt = 3, sub = 0}
(gdb) next

Thread 2 "SubeventExample" received signal SIGSEGV, Segmentation fault.
0x000000000043307e in JFactoryT<MyOutput>::ClearData (this=0x7ffff02f5bd0)
    at /home/davidl/work/2022.11.13.JANA2_CUDA/JANA2_cissieAB/src/libraries/JANA/JFactoryT.h:214
214	            for (auto p : mData) delete p;
~~~


Run with CPU
-----------------------------------------------------------------
~~~bash
Thread 2 "SubeventExample" hit Breakpoint 1, JFactoryT<MyInput>::ClearData (this=0x7ffff0001e50)
    at /home/davidl/work/2022.11.13.JANA2_CUDA/JANA2_cissieAB/src/libraries/JANA/JFactoryT.h:214
214	            for (auto p : mData) delete p;
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64
(gdb) print *mData[0]
$1 = {<JObject> = {_vptr.JObject = 0x59c528 <vtable for MyInput+16>, associated = std::set with 0 elements, auto_delete = std::set with 0 elements}, 
  x = 22, y = 3.5999999, evt = 3, sub = 0}
(gdb) cont
Continuing.

Thread 2 "SubeventExample" hit Breakpoint 1, JFactoryT<MyOutput>::ClearData (this=0x7ffff0003a00)
    at /home/davidl/work/2022.11.13.JANA2_CUDA/JANA2_cissieAB/src/libraries/JANA/JFactoryT.h:214
214	            for (auto p : mData) delete p;
(gdb) print *mData[0]
$2 = {<JObject> = {_vptr.JObject = 0x59c4f8 <vtable for MyOutput+16>, associated = std::set with 0 elements, auto_delete = std::set with 0 elements}, 
  z = 25.6000004, evt = 3, sub = 0}
~~~

**Comment by cissieAB** [comment]
@faustus123 Yes, it works after adding the line!

Thank you, I learned gdb skills from you!

**Comment by faustus123** [comment]
I just noticed your request to be added to this repository. I just now did this. You should have received an invite.

**Comment by cissieAB** [comment]
@faustus123 Thank you for adding me in! I am able to edit the PR now!

**Comment by nathanwbrei** [comment]
We should add a USE_CUDA flag to our CMake config (the same way as USE_ASAN, etc) and set it so that we only build SubeventCUDAExample when USE_CUDA=On. That way our current CI systems don't fail so we can merge this.

**Comment by nathanwbrei** [comment]
The next step is to generalize this so that the kernel takes n inputs and outputs instead of 1. Then we can start testing the performance of the whole event collating

**Comment by cissieAB** [comment]
CI test is passed.

**Pull request merged**
