### PR TITLE
Remove spurious 'f'.

### PR DESCRIPTION
**Pull request by faustus123**
Not sure how this got there or why it didn't cause problems before.

### CODE REVIEW

**Comment by nathanwbrei** [comment]
That isn't a spurious 'f', it's a Python f-string, which has been part of the language since 3.6. You are probably running an old Python3 on CUE. 

https://realpython.com/python-f-strings/

**Comment by faustus123** [comment]
OK. So is it needed?


Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist - - EPSCI Group Lead
Thomas Jefferson National Accelerator Facility
Newport News, VA
***@***.******@***.***>
(757) 269-5567 W
(757) 746-6697 C


On Feb 14, 2022, at 2:24 PM, Nathan Brei ***@***.******@***.***>> wrote:



That isn't a spurious 'f', it's a Python f-string, which has been part of the language since 3.6. You are probably running an old Python3 on CUE.

https://realpython.com/python-f-strings/<https://urldefense.proofpoint.com/v2/url?u=https-3A__realpython.com_python-2Df-2Dstrings_&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=i0p-C_T1RieVsCZl8ZnUyQ&m=auRPbuZtnSj5kCj5_BFsTiVSYhFh2GF7yvKR64m7ht_rZzATr_5rarFc2fzI8BTL&s=JY5RFBT5bu9FAGeKN785SuTFQO9k2-k9Kkm0eIjhwnk&e=>

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_JANA2_pull_103-23issuecomment-2D1039466127&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=i0p-C_T1RieVsCZl8ZnUyQ&m=auRPbuZtnSj5kCj5_BFsTiVSYhFh2GF7yvKR64m7ht_rZzATr_5rarFc2fzI8BTL&s=YgE236JORvBJ7WnCdYKgJx37Yv5SywqzAnqa9gpE_qo&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADB6NZILFO6C7UYBJSJ6B3TU3FJHXANCNFSM5OHSDTBQ&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=i0p-C_T1RieVsCZl8ZnUyQ&m=auRPbuZtnSj5kCj5_BFsTiVSYhFh2GF7yvKR64m7ht_rZzATr_5rarFc2fzI8BTL&s=pSYhvh-DFtJiWg0JpfmAaFO-zpegqIcXY6WkHhJhx6Y&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=i0p-C_T1RieVsCZl8ZnUyQ&m=auRPbuZtnSj5kCj5_BFsTiVSYhFh2GF7yvKR64m7ht_rZzATr_5rarFc2fzI8BTL&s=FMcrbb9YoAhMZhVC4SGo5RMknrA_D99GRKkM1ybA7Gc&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=i0p-C_T1RieVsCZl8ZnUyQ&m=auRPbuZtnSj5kCj5_BFsTiVSYhFh2GF7yvKR64m7ht_rZzATr_5rarFc2fzI8BTL&s=67ajKH7UkZJc2EsI7j8VVEuMRJcySulx2dbsOWht2d0&e=>.

**Comment by nathanwbrei** [comment]
That particular line is not needed, but I highly doubt that's the only f-string in JANA. f-strings provide a definite ergonomics/readability advantage over the 20 other ways of formatting strings in Python. Python 3.6 came out in 2016, I don't feel like that's a huge ask.  I vote we default CUE to a more recent version of Python instead.

**Comment by nathanwbrei** [comment]
Agreed. I'll add that in with the other fix.

**Pull request closed without merging**
