### PR TITLE
[doc] Some parts from Concepts moved to index page and rewritten.

### PR DESCRIPTION
**Pull request by DraTeots**
- Moved philosophy part from Concepts to index page and updated the text. The idea is to have the index page more about JANA2 general stuff like history, philosophy, motivation, etc. And have Concepts page to be dedicated to technical concepts, like what are factories and other main elements, how they differ and how they play together. It is to be done/written.

### CODE REVIEW

**Comment by nathanwbrei** [comment]
Looks extremely reasonable. Want me to merge this now, or are there more changes you'd like to put in here?

**Comment by DraTeots** [comment]
> Looks extremely reasonable. Want me to merge this now, or are there more changes you'd like to put in here?

Converted to draft. Let me put some other related changes then.

**Comment by nathanwbrei** [comment]
Is this something you want to merge pretty soon as well?

**Comment by nathanwbrei** [comment]
Here are some more documentation improvements!

The items buried under "Other Howtos" are extremely important (e.g. how to build and install), and the ones under the parent "Howtos" are a lot less important. I'm guessing you ordered them this way because of how the content was split among the underlying markdown files, which you are free to change however you see fit. 

One final nitpick: the "Howtos" doesn't collapse like the other sidebar sections do.

**Comment by DraTeots** [comment]
1. If you [look at _sidebar.md](https://raw.githubusercontent.com/JeffersonLab/JANA2/master/docs/_sidebar.md) code, HowTo-s are a sublist, while all others are links to a single .md files. Collapsing actually works the opposite way. Docsify doesn't collapse group of documents but **expands** single document content based on its headers (or \# and \#\# in markdown). 

I believe it is important to explain here, as the system is new and I would like everybody to be onboard with its capabilities (as wanted to copy it to other projects). You have global configuration of how things collapse and one can [disable such behaviour for each particular title/header/subheaders](https://docsify.js.org/#/more-pages?id=ignoring-subheaders) with `<!-- {docsify-ignore} -->` and `<!-- {docsify-ignore-all} -->`

`JANA1 to 2` and `Development` consists of several `.md` files, but we combine them together in one document like here: 

- [combining development together](https://github.com/JeffersonLab/JANA2/blob/master/docs/development/development.md?plain=1#L3) and 
- [combining jana1to2 together](https://github.com/JeffersonLab/JANA2/blob/master/docs/jana1to2/jana1-to-jana2.md?plain=1#L14): 

So I experimented, how it looks making e.g. `JANA1 to 2` as sub-list like how-tos or combined document and thought it is much more convenient as one document. E.g. developer has one point of entry, then have full list to choose a topic they are looking for, etc. 

2. "Other Howtos". All how-tos section needs love and rework. I just moved whatever was there. If you create a ticket with the priorities and what you think as the most important discussions, I will be happy to follow it and reorganize it. Or I can try to think about it myself not putting more load on you =P. 

But the idea so far was to put things from the old site as it and start reworking them one by one. I now try to dedicate a fraction of time every week to work on the documentation. Currently I am stuck on writing concepts with factories, processors and stuff. So let me know if you think of other priorities.

**Pull request merged**
