### PR TITLE
fix: JEventGroupManager is final

### PR DESCRIPTION
**Pull request by wdconinc**
This addresses a clang warning.

### CODE REVIEW

**Comment by nathanwbrei** [comment]
Thanks, Wouter! I haven't seen this warning before, what clang version are you using? 
In the last week I've addressed all but one of the warnings emitted by gcc11. Hopefully the next release will compile with no warnings on any of the main compilers we care about.

**Comment by wdconinc** [comment]
clang-15, under development.

**Comment by faustus123** [comment]
I haven't looked at this, but does it give the reasoning why this should be made final (as opposed to all of the other classes)?

**Comment by wdconinc** [comment]
The destructor is final, which forces the class as final too.

**Comment by nathanwbrei** [comment]
I don't remember exactly _why_ I made the JEventGroupManager destructor final. (I do remember that there are some important invariants that need to be maintained in order for JApplication::Run to always terminate, and this isn't something we want users mucking with) Looking back, it's way clearer (and accomplishes the same thing) to make the class final instead.

**Comment by wdconinc** [comment]
Probably should remove the destructor final then and completely defer to class final.

**Pull request merged**
