### PR TITLE
JEventProcessorSequential

### PR DESCRIPTION
**Pull request by faustus123**
This (partially) addresses the second bullet in section 3.1 of Ole's review document which concerns having a JEventProcessor class where the user does not need to lock a mutex themselves. It is in the form of a single, header-only defined class and requires no other changes to the JANA source.

This only partially addresses the issue since it uses its own internal mutex as the sequential lock rather than the global ROOT lock. The largest use case for this feature will be for interacting with ROOT so that will be needed as well. That will come in a future PR and should be a nearly identical class as this.

### CODE REVIEW

**Comment by nathanwbrei** [comment]
I hate to be the bearer of bad news, but I'm worried this has a race condition. On the bright side, I think it's fixable. Your Prefetch::Get(event) is writing the contents of a factory _for each event_ into a single Prefetch object in parallel. The Prefetch vectors needs to be organized by event number. Inserting a new vector of object pointers for any event number needs to be protected via a lock. Finally, you'll need to clear out the prefetched vector after ProcessSequential has run (both for memory safety, because those pointers will get deleted, and to avoid a memory leak) and this clear operation needs to be protected with the same lock.

**Comment by nathanwbrei** [comment]
Here's a cleaner idea than what I suggested above. 

Change PrefetchT::Get so that it calls JEvent::Get() to trigger the expensive computation in parallel but DOESN'T fill the mObjs vector. 
Create PrefetchT::Fill, which calls JEvent::Get() again and this time fills the buffer. 
Create PrefetchT::Clear, which clears the buffer.

Call them like this:
```c++
	void Process(const std::shared_ptr<const JEvent>& event) override final{
		for( auto p : mPrefetch ) p->Get(event);

		std::lock_guard<std::mutex> lck(mMutex);

		for( auto p : mPrefetch ) p->Fill(event);
		ProcessSequential( event );
		for( auto p : mPrefetch ) p->Clear();
	}
```

**Comment by faustus123** [comment]
D'oh. Not sure how I missed that before.

I agree that your second comment is a clean way to handle it with virtually no additional overhead.

**Comment by nathanwbrei** [comment]
Should be a super easy change. Should we try to get it in the next tagged release as well?

**Comment by faustus123** [comment]
Just made the change and added a ROOT version as discussed earlier. Completely untested still so hold off on merging until that is done.

**Pull request merged**
