### PR TITLE
v2.0.7 fixes

### PR DESCRIPTION
**Pull request by faustus123**
This is a bit of a hack and may need to be cleaned up. It illustrates what is need though to get this working with EICrecon

### CODE REVIEW

**Comment by nathanwbrei** [comment]
What you have looks fine for now, but I think the root problem is that the target_include_directories aren't being set on the JANA:jana2 target.

**Comment by nathanwbrei** [comment]
I don't understand this modern CMake nonsense well enough to fix it quickly, so let's merge what you have and fix it in the next release. Maybe @veprbl can help.

**Comment by veprbl** [comment]
I have no comment on this other than that all five of the last `set(`'s should be removed eventually.

**Comment by nathanwbrei** [comment]
@veprbl I'm perfectly happy to revert your changes and keep using old-style CMake.

**Pull request merged**
