### PR TITLE
355 jana1 2 documentation side menu

### PR DESCRIPTION
**Pull request by DraTeots**
- Combine documents together and adds to a side menu. I played with how it is easier to conceive new addition in the menu and easier to navigate so that is why there are drastic changes. 
- Edited developers guide. Made it easier to read in editing mode as well as to properly highlight all c++ code. 
- Added documentation on how to manage and write the documentation. In particular how one can play with the site on a local machine. 

I probably did something that hasn't been asked, please no offence here. But I just wanted to make it more accessible and easier to read.

### CODE REVIEW

**Comment by DraTeots** [comment]
I believe it makes https://github.com/JeffersonLab/JANA2/pull/356 obsolete. I saw it too late. Sorry.

**Comment by DraTeots** [comment]
image
That is how it looks now (so you don't have to startup a local server)

**Comment by nathanwbrei** [comment]
While you are working on this, it looks like https://jeffersonlab.github.io/JANA2/#/tutorial is a broken link?

**Comment by nathanwbrei** [comment]
If it makes your workflow faster, you can merge the documentation changes without waiting for all the other tests to complete

**Comment by DraTeots** [comment]
> If it makes your workflow faster, you can merge the documentation changes without waiting for all the other tests to complete

I would prefer @RaiqaRasool to look at changes too. But I feel urgency to merge this PR to prevent security issue with any PR pushing changes to a website.

**Comment by DraTeots** [comment]
So, please, make another issue or PR if something is bad here.

**Pull request merged**
