### PR TITLE
Revise CI to add BlockExample tests in

### PR DESCRIPTION
**Pull request by cissieAB**
To make life easier at JANA4ML4FPGA side.

### CODE REVIEW

**Comment by cissieAB** [comment]
https://github.com/JeffersonLab/JANA2/actions/runs/4351088097/jobs/7602399634

⬆️  @faustus123 the CI for BlockExample test returns a "segment fault", though I think it's not related to `jana4ml4fpga -v` double free error.

**Comment by faustus123** [comment]
It looks like this includes changes to [JEventSourceArrow.cc](https://github.com/JeffersonLab/JANA2/pull/203/files#diff-781f5cb181b46931dbb41561ccc11523561eb7798e3357858c29960dab991778) that reverse the fix recently put in in PR #200. Make sure those lines aren't deleted when the PR is changed from draft to full PR.

**Comment by cissieAB** [comment]
See my comments in issue #207. It failed and threw exception in Disentangle block in one, but passed on my own notebook and another CI try.

Anyway, this does not influence merging this PR since the commit does not touch any core codebase.

**Review by faustus123 — APPROVED** [review]
This is odd because `BlockExample.so` is not actually a plugin, but has been given a `.so` suffix and is installed in the "plugins" directory. This is probably because it was copied from SubeventExample which is also wrong.

I will approve this for now since it technically works. We will need to overhaul the examples directory to fix all of these errors in a separate PR.

**Pull request merged**
